### ISSUE TITLE
implement swsearch.py

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#11]
- need to implement a simplified version of grep for swift with simple substring search
- should search all files / objects including multi-segment objects under the requested container/prefix
- parallel search (even if RAM intensive)
- would ideally open first xxx bytes to determine if binary or text file/object and skip binary (most solutions seem to look for null character to determine binary or not  --- e.g. http://stackoverflow.com/questions/898669/how-can-i-detect-if-a-file-is-binary-non-text-in-python)
- display entire line with line number in matching result (unix and windows line breaks) 

advanced features: 
- meta data search filter --meta=key:value 
- grep compatible regular expression search

**Comment by dirkpetersen** [comment]
also we need to add a prefix option

```
parser.add_argument( '--prefix', '-p', dest='prefix',
```

args.prefix is passed to get_container to limit the number of objects to search based on pseudo folder

**Comment by dirkpetersen** [comment]
if the search string occurs in the name of the object could the output say something like this ?

objectfolder/someobject: matched object name

**Comment by jmkatcher** [comment]
The object name is at least currently, not searched.

I have a really weird bug now, where execution just vanishes.  Even if the next function is undeclared, it won’t even error.  Some kind of MP thing….
