### ISSUE TITLE
Improve packaging of swift-commander

### ISSUE THREAD

**Issue by jtratner** [FredHutch/swift-commander#14]
We're interested in using swift-commander at work because of how easy it is to use and the low barrier to entry to using it.  That said, it's a little hard to install swift-commander on to a system (and to upgrade swift-commander if a new version comes out), because it's not really packaged.

My suggestion is to make this library pip installable and then use the console-scripts entry point to provide swc and its supporting python files.  This also would make swift-commander support virtualenvs, and make it trivial to version the library. The installation story would then be:

```
pip install swift-commander
```

And then `swc` and related utilities would all become available in the environment.

If you folks are receptive to this idea, I'm happy to put up a pull request that makes this happen. It'd mean moving around the file hierarchy slightly but overall it'd be a pretty trivial change.

In a similar vein, is there a reason that the `*.py` files are all hardcoded to be python3 only?

**Comment by dirkpetersen** [comment]
You are right, Jeff. Packaging would be nice. We have put it into a shared nfs mount that can be accessed by all users but I understand that others prefer a much different setup.  I would greatly appreciate a pull request. It would have to support the use case where you put all files into a single folder and add that to the path. Is this possible?   Jeff, any thoughts?

Re python3: We use python2 and python3 and have many different minor versions installed. The reason we enforce python3 is that we have not been testing with python2 at all, it would just take too many resources as we have not been developing test cases.

**Comment by jtratner** [comment]
@dirkpetersen - put a PR together that accomplishes your goals and still keeps the default shebang for Python 3.

How do you currently test your changes to swc? Could you send me some manual test cases?

In terms of Python 2, for our set up we currently only have Python 2 installed. I actually did not realize `swc` required Python 3, because it worked just fine with Python 2.X.  After we make `swc` pip installable, I'd like to quickly go through and tweak anything that doesn't work with 2.X so it works with both Python 2 and Python 3 (and just claim only official support for Python 3).  After that, there will at least be one version of `swc` that can work with Python 2.
