### ISSUE TITLE
swrm.py python2 issue - NameError: 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#22]
root@lxdtest1:~# swc rm /test13/var
  (..using token credentials from environment)
using account :
...swrm.py -c test13 -p var
    deleting /test13/var ... 
Error 404 deleting object var: ClientException('Object DELETE failed',)
    checking swift folder /test13/var/ ...
    checking size of /test13/var/ ... 
        found 40 files with 16,683,465 bytes (15.911 MB) in /test13/var/
    Do you want to delete this data in account AUTH_Swift__ADM_SciComp ? (y/N) y
Traceback (most recent call last):
  File "/usr/local/bin/swrm.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/swift_commander/swrm.py", line 67, in main
    if yn_choice("    Do you want to delete this data in account %s ?" % swaccount):
  File "/usr/local/lib/python2.7/dist-packages/swift_commander/swrm.py", line 119, in yn_choice
    choice = input("%s (%s) " % (message, choices))
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by CountDracula** [comment]
FYI, looks like this error can be circumvented by quoting the value in the prompt, e.g. "y" or "yes"

**Comment by dirkpetersen** [comment]
I cannot reproduce this with python3
