### ISSUE TITLE
swc fails silently when authentication token expires and executed via sbatch 

### ISSUE THREAD

**Issue by bdconnolly** [FredHutch/swift-commander#25]
To repro this bug do the following 

1. Find a file on the economy files to download 
2. ssh to rhino 
3. Run `sw2acccount ACCOUNTNAME` and choose the container where the file is located 
4. Now run swc to download a file 
    
    `swc download /ECONOMY/FILE/PATH . `
    
5. This step should work. Delete the downloaded file from the current directory. 
6. Now lets create a slurm job script to execute the download. Name the file `job1.sh` The file contents will be 
    
    ```
    #!/bin/bash
    #SBATCH -N1
    echo "Output to show script running"
    swc download /ECONOMY/FILE/PATH . 
    hostname 
    ```
    
7.  Expire your auth token changing the date of the file `~/.swift/auth_token_tin.fhcrc.org_v2_AUTH_Swift_ACCOUNTNAME` to atleast one day in the past, ie   
     
    ```
    touch -d "2004-02-29 16:21:42" ~/.swift/auth_token_tin.fhcrc.org_v2_AUTH_Swift_hsieh_a
    ```
    
8. Submit the job to gizmo cluster by running `sbatch job1.sh`
9. The job will complete successfully, but you will notice that the file does not get downloaded.  And the slurm output file will show something like 
    
    ```
    Output to show script running
    gizmof60
    ```
    
10. Now lets run this script, `job1.sh` directly on rhino. When it is run, you will see 
    
    ```
    Output to show script running
    Enter your swift password/key for bconnoll:
    ```
    
11. After you enter your password the file will download. 

From my testing it looks like when run via sbatch the request for me to enter my credentials silently ignored and swc command completes with a 0 exit code.  We should make sure the swc script outputs a message in this scenario so that he user knows them need to successfully authenticate before they execute the sbatch command again. 

[See ticket 129043 for an example of this happening in the real world]

**Comment by dirkpetersen** [comment]
This is fixed, if the prompt comes and expires because there is no password entered within the timeout period there is now an error message and the script exits with error code 1

 "Error: Token expired or no password entered within timeout period."
