### ISSUE TITLE
swc unarch (swbundler) fails silently 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#28]
I used this command archive a 40GB folder 

swc archive "/fh/fast/kiem_h/grp/kiemlab/LAB MEMBERS/Past Lab Members/Bonan" "/kiem_h/LAB MEMBERS/Past Lab Members/Bonan"

The size seems OK as swbundler uses pigz compression:

```
swc size "/kiem_h/LAB MEMBERS/Past Lab Members/Bonan"
    checking swift folder kiem_h/LAB MEMBERS/Past Lab Members/Bonan ...
    24,480,267,611 bytes (22.799 GB) in kiem_h/LAB MEMBERS/Past Lab Members/Bonan (swift)
```

But when I try  to extract it , I stops after 1 sec without error message 

```
swc unarch "/kiem_h/LAB MEMBERS/Past Lab Members/Bonan" /fh/scratch/delete10/_ADM/SciComp/petersen/
*** downloading to /fh/scratch/delete10/_ADM/SciComp/petersen/ ***
*** from AUTH_Swift__ADM_SciComp:/kiem_h/LAB MEMBERS/Past Lab Members/Bonan ***
executing:swbundler.py -x -l "/fh/scratch/delete10/_ADM/SciComp/petersen/" -c kiem_h -p "LAB MEMBERS/Past Lab Members/Bonan" -t "/tmp/petersen.rqdUW"
*** please wait... ***
/kiem_h/LAB MEMBERS/Past Lab Members/Bonan

```

**Comment by dirkpetersen** [comment]
swbundler.py is currently installed at /app/lib/swc/

**Comment by dirkpetersen** [comment]
it correctly loops over a list of objects and passes them into this pool. I guess this parallelization machinery has changed https://github.com/FredHutch/swift-commander/blob/master/swift_commander/swbundler.py#L365

**Comment by jmkatcher** [comment]
The reason this fails silently is that the error condition is in a multiprocessing Pool object, which does not propagate the error back to the parent Python process on failure.

**Comment by jmkatcher** [comment]
Found there was a new default parameter conflict in swiftclient - deleted explicit '-p' (retaining '--prompt') to eliminate.  Also made -P 1 _not_ use multiprocessing for the sake of future debugging.
